package main

func main() {

	// PrintHelloWorld()
	// ArrayModule()
	// BoolOperator()
	// BoolModule()
	// BreakModule()
	// ClosureModule()
	// ComparisonOperator()
	// ConstantModule()
	// ContainerListModule()
	// ContainerRingModule()
	// ContinueModule()
	// ConversionModule()

	// DeferModule()

	// FlagModule()
	// ForLoopsModule()
	// AnonymousFuncModule()
	// FuncAsParameterModule()
	// FuncAsValueModule()
	// FuncRecursiveModule()
	// FuncReturnMultipleValueModule()
	// FuncReturnNamedValue()
	// FuncReturnValueModule()
	// FuncVariadicModule()
	// FuncModule()
	// IfStatementModule()
	// ImportModule()
	// InterfaceErrorModule()
	// InterfaceModule()
	// MapModule()
	// MathModule()
	// NilModule()
	// NumberModule()
	// OSModule()
	// PanicModule()
	// PointerMethodModule()
	// PointerModule()
	// RecoverModule()
	// ReflectModule()
	// RegexpModule()
	// SliceModule()
	// SortModule()
	// StrconvModule()
	// StringModule()
	// StringsModule()
	// StructModule()
	// SwitchModule()
	// TimeModule()
	// TypeAssertionModule()
	// TypeDeclarationsModule()
	// VariablesModule()

}
